global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
    basic_auth:
      username: 2470523
      password: "<GRAFANA_API_TOKEN>"
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "moodai-backend"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["host.docker.internal:4000"]
